#!/bin/bash

cd "$(dirname "$0")"
 
read -p 'commit name: ' commit

if [ -z "$commit"]
then
    echo "bruh moment"
    commit="autosave"
fi

git commit -am $commit
git push origin master
git push heroku master